import { createStitches, createTheme, globalCss } from "@stitches/react";
export type { VariantProps } from "@stitches/react";
import * as tokens from "@mira-ds/design-tokens";

// export const globalStyles = globalCss({
//   "*": { margin: 0, fontFamily: "$poppins, sans-serif" },
//   "*::before": {
//     boxSizing: "border-box",
//   },
//   "*::after": {
//     boxSizing: "border-box",
//   },
//   body: {
//     lineHeight: 1.5,
//     WebkitFontSmoothing: "antialiased",
//   },
//   img: {
//     display: "block",
//     maxWidth: "100%",
//   },
//   picture: {
//     display: "block",
//     maxWidth: "100%",
//   },
//   video: {
//     display: "block",
//     maxWidth: "100%",
//   },
//   canvas: {
//     display: "block",
//     maxWidth: "100%",
//   },
//   svg: {
//     display: "block",
//     maxWidth: "100%",
//   },
// });

export const { styled, getCssText, theme, css } = createStitches({
  utils: {
    px: (value: any) => ({
      paddingLeft: value,
      paddingRight: value,
    }),
    mb: (value: any) => ({
      marginBottom: value,
    }),
    my: (value: any) => ({
      marginTop: value,
      marginBottom: value,
    }),
    py: (value: any) => ({
      paddingTop: value,
      paddingBottom: value,
    }),
  },
  media: {
    bp1: `(min-width: 520px)`,
    bp2: `(min-width: 900px)`,
    bp3: `(min-width: 1200px)`,
    bp4: `(min-width: 1800px)`,
    motion: "(prefers-reduced-motion)",
    dark: "(prefers-color-scheme: dark)",
    light: "(prefers-color-scheme: light)",
  },
  theme: {
    fonts: {
      system: "system-component-library",
      recursive: "Recursive",
      poppins: '"Poppins", sans-serif',
    },
    colors: {
      hiContrast: "hsl(206,10%,5%)",
      loContrast: tokens.COLOR_BASE_WHITE,
      red1: tokens.COLOR_BASE_RED_1,
      red2: tokens.COLOR_BASE_RED_2,
      red3: tokens.COLOR_BASE_RED_3,
      red4: tokens.COLOR_BASE_RED_4,
      red5: tokens.COLOR_BASE_RED_5,
      red6: tokens.COLOR_BASE_RED_6,
      red7: tokens.COLOR_BASE_RED_7,
      red8: tokens.COLOR_BASE_RED_8,
      red9: tokens.COLOR_BASE_RED_9,
      red10: tokens.COLOR_BASE_RED_10,
      red11: tokens.COLOR_BASE_RED_11,
      red12: tokens.COLOR_BASE_RED_12,
      green1: tokens.COLOR_BASE_GREEN_1,
      green2: tokens.COLOR_BASE_GREEN_2,
      green3: tokens.COLOR_BASE_GREEN_3,
      green4: tokens.COLOR_BASE_GREEN_4,
      green5: tokens.COLOR_BASE_GREEN_5,
      green6: tokens.COLOR_BASE_GREEN_6,
      green7: tokens.COLOR_BASE_GREEN_7,
      green8: tokens.COLOR_BASE_GREEN_8,
      green9: tokens.COLOR_BASE_GREEN_9,
      green10: tokens.COLOR_BASE_GREEN_10,
      green11: tokens.COLOR_BASE_GREEN_11,
      green12: tokens.COLOR_BASE_GREEN_12,
      blue1: tokens.COLOR_BASE_BLUE_1,
      blue2: tokens.COLOR_BASE_BLUE_2,
      blue3: tokens.COLOR_BASE_BLUE_3,
      blue4: tokens.COLOR_BASE_BLUE_4,
      blue5: tokens.COLOR_BASE_BLUE_5,
      blue6: tokens.COLOR_BASE_BLUE_6,
      blue7: tokens.COLOR_BASE_BLUE_7,
      blue8: tokens.COLOR_BASE_BLUE_8,
      blue9: tokens.COLOR_BASE_BLUE_9,
      blue10: tokens.COLOR_BASE_BLUE_10,
      blue11: tokens.COLOR_BASE_BLUE_11,
      blue12: tokens.COLOR_BASE_BLUE_12,
      orange1: tokens.COLOR_BASE_ORANGE_1,
      orange2: tokens.COLOR_BASE_ORANGE_2,
      orange3: tokens.COLOR_BASE_ORANGE_3,
      orange4: tokens.COLOR_BASE_ORANGE_4,
      orange5: tokens.COLOR_BASE_ORANGE_5,
      orange6: tokens.COLOR_BASE_ORANGE_6,
      orange7: tokens.COLOR_BASE_ORANGE_7,
      orange8: tokens.COLOR_BASE_ORANGE_8,
      orange9: tokens.COLOR_BASE_ORANGE_9,
      orange10: tokens.COLOR_BASE_ORANGE_10,
      orange11: tokens.COLOR_BASE_ORANGE_11,
      orange12: tokens.COLOR_BASE_ORANGE_12,
      gray1: tokens.COLOR_BASE_GREY_1,
      gray2: tokens.COLOR_BASE_GREY_2,
      gray3: tokens.COLOR_BASE_GREY_3,
      gray4: tokens.COLOR_BASE_GREY_4,
      gray5: tokens.COLOR_BASE_GREY_5,
      gray6: tokens.COLOR_BASE_GREY_6,
      gray7: tokens.COLOR_BASE_GREY_7,
      gray8: tokens.COLOR_BASE_GREY_8,
      gray9: tokens.COLOR_BASE_GREY_9,
      gray10: tokens.COLOR_BASE_GREY_10,
      gray11: tokens.COLOR_BASE_GREY_11,
      gray12: tokens.COLOR_BASE_GREY_12,
      cardBg: tokens.COLOR_BASE_WHITE,
    },
    fontSizes: {
      tiny: `${tokens.SIZE_FONT_TINY}rem`,
      small: `${tokens.SIZE_FONT_SMALL}rem`,
      medium: `${tokens.SIZE_FONT_MEDIUM}rem`,
      large: `${tokens.SIZE_FONT_LARGE}rem`,
      xxl: `${tokens.SIZE_FONT_XXL}rem`,
      xxxl: `${tokens.SIZE_FONT_XXXL}rem`,
      1: "12px",
      2: "14px",
      3: "16px",
      4: "17px",
      5: "19px",
      6: "21px",
      7: "27px",
      8: "35px",
      9: "59px",
      10: "72px",
      11: "96px",
    },
    space: {
      tiny: tokens.SIZE_SPACING_TINY,
      small: tokens.SIZE_SPACING_SMALL,
      medium: tokens.SIZE_SPACING_MEDIUM,
      large: tokens.SIZE_SPACING_LARGE,
      xxl: tokens.SIZE_SPACING_XXL,
      xxxl: tokens.SIZE_SPACING_XXXL,
    },
    zIndices: {
      beneath: -1,
      normal: "auto",
      onTop: 10,
    },
    fontWeights: {
      1: "300",
      2: "400",
      3: "500",
      4: "600",
      5: "700",
      6: "800",
      7: "900",
      bold: "bold",
    },
    borderWidths: {
      1: "1px",
      2: "2px",
      3: "5px",
      4: "10px",
      5: "25px",
    },
    radii: {
      small: tokens.SIZE_RADII_SMALL,
      medium: tokens.SIZE_RADII_MEDIUM,
      large: tokens.SIZE_RADII_LARGE,
    },
  },
});

export const darkTheme = createTheme({
  colors: {
    loContrast: "hsl(206,10%,5%)",
    red1: tokens.COLOR_BASE_RED_INVERSE_1,
    red2: tokens.COLOR_BASE_RED_INVERSE_2,
    red3: tokens.COLOR_BASE_RED_INVERSE_3,
    red4: tokens.COLOR_BASE_RED_INVERSE_4,
    red5: tokens.COLOR_BASE_RED_INVERSE_5,
    red6: tokens.COLOR_BASE_RED_INVERSE_6,
    red7: tokens.COLOR_BASE_RED_INVERSE_7,
    red8: tokens.COLOR_BASE_RED_INVERSE_8,
    red9: tokens.COLOR_BASE_RED_INVERSE_9,
    red10: tokens.COLOR_BASE_RED_INVERSE_10,
    red11: tokens.COLOR_BASE_RED_INVERSE_11,
    red12: tokens.COLOR_BASE_RED_INVERSE_12,
    green1: tokens.COLOR_BASE_GREEN_INVERSE_1,
    green2: tokens.COLOR_BASE_GREEN_INVERSE_2,
    green3: tokens.COLOR_BASE_GREEN_INVERSE_3,
    green4: tokens.COLOR_BASE_GREEN_INVERSE_4,
    green5: tokens.COLOR_BASE_GREEN_INVERSE_5,
    green6: tokens.COLOR_BASE_GREEN_INVERSE_6,
    green7: tokens.COLOR_BASE_GREEN_INVERSE_7,
    green8: tokens.COLOR_BASE_GREEN_INVERSE_8,
    green9: tokens.COLOR_BASE_GREEN_INVERSE_9,
    green10: tokens.COLOR_BASE_GREEN_INVERSE_10,
    green11: tokens.COLOR_BASE_GREEN_INVERSE_11,
    green12: tokens.COLOR_BASE_GREEN_INVERSE_12,
    blue1: tokens.COLOR_BASE_BLUE_INVERSE_1,
    blue2: tokens.COLOR_BASE_BLUE_INVERSE_2,
    blue3: tokens.COLOR_BASE_BLUE_INVERSE_3,
    blue4: tokens.COLOR_BASE_BLUE_INVERSE_4,
    blue5: tokens.COLOR_BASE_BLUE_INVERSE_5,
    blue6: tokens.COLOR_BASE_BLUE_INVERSE_6,
    blue7: tokens.COLOR_BASE_BLUE_INVERSE_7,
    blue8: tokens.COLOR_BASE_BLUE_INVERSE_8,
    blue9: tokens.COLOR_BASE_BLUE_INVERSE_9,
    blue10: tokens.COLOR_BASE_BLUE_INVERSE_10,
    blue11: tokens.COLOR_BASE_BLUE_INVERSE_11,
    blue12: tokens.COLOR_BASE_BLUE_INVERSE_12,
    orange1: tokens.COLOR_BASE_ORANGE_INVERSE_1,
    orange2: tokens.COLOR_BASE_ORANGE_INVERSE_2,
    orange3: tokens.COLOR_BASE_ORANGE_INVERSE_3,
    orange4: tokens.COLOR_BASE_ORANGE_INVERSE_4,
    orange5: tokens.COLOR_BASE_ORANGE_INVERSE_5,
    orange6: tokens.COLOR_BASE_ORANGE_INVERSE_6,
    orange7: tokens.COLOR_BASE_ORANGE_INVERSE_7,
    orange8: tokens.COLOR_BASE_ORANGE_INVERSE_8,
    orange9: tokens.COLOR_BASE_ORANGE_INVERSE_9,
    orange10: tokens.COLOR_BASE_ORANGE_INVERSE_10,
    orange11: tokens.COLOR_BASE_ORANGE_INVERSE_11,
    orange12: tokens.COLOR_BASE_ORANGE_INVERSE_12,
    gray1: tokens.COLOR_BASE_GREY_INVERSE_1,
    gray2: tokens.COLOR_BASE_GREY_INVERSE_2,
    gray3: tokens.COLOR_BASE_GREY_INVERSE_3,
    gray4: tokens.COLOR_BASE_GREY_INVERSE_4,
    gray5: tokens.COLOR_BASE_GREY_INVERSE_5,
    gray6: tokens.COLOR_BASE_GREY_INVERSE_6,
    gray7: tokens.COLOR_BASE_GREY_INVERSE_7,
    gray8: tokens.COLOR_BASE_GREY_INVERSE_8,
    gray9: tokens.COLOR_BASE_GREY_INVERSE_9,
    gray10: tokens.COLOR_BASE_GREY_INVERSE_10,
    gray11: tokens.COLOR_BASE_GREY_INVERSE_11,
    gray12: tokens.COLOR_BASE_GREY_INVERSE_12,
    cardBg: "hsl(206,10%,15%)",
  },
});
