// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "1": "0.875rem",
 "2": "1rem",
 "3": "1.125rem",
 "4": "1.25rem",
 "5": "1.625rem",
 "6": "2rem",
 "7": "2.5rem",
 "8": "3rem"
} as const;

export default fontSizes;