// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
 "1": "520px",
 "2": "768px",
 "3": "900px",
 "4": "1200px"
} as const;

export default mediaQueries;