// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "1": "0.5rem",
 "2": "1rem",
 "3": "1.5rem",
 "4": "2rem",
 "5": "2.5rem",
 "6": "3rem",
 "7": "3.5rem",
 "xs": "0.375rem"
} as const;

export default spacing;