// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "red11": "rgba(206, 44, 49, 1)",
 "red10": "rgba(219, 61, 66, 1)",
 "red9": "rgba(229, 72, 77, 1)",
 "red8": "rgba(235, 142, 144, 1)",
 "red7": "rgba(243, 175, 176, 1)",
 "red6": "rgba(249, 199, 199, 1)",
 "red5": "rgba(253, 216, 216, 1)",
 "red4": "rgba(255, 230, 230, 1)",
 "red3": "rgba(255, 240, 240, 1)",
 "red2": "rgba(255, 250, 250, 1)",
 "red1": "rgba(255, 251, 251, 1)",
 "blue12": "rgba(0, 37, 77, 1)",
 "blue11": "rgba(0, 106, 219, 1)",
 "blue10": "rgba(0, 128, 240, 1)",
 "blue9": "rgba(0, 145, 255, 1)",
 "blue8": "rgba(93, 176, 239, 1)",
 "blue7": "rgba(151, 199, 242, 1)",
 "blue6": "rgba(181, 215, 247, 1)",
 "blue5": "rgba(205, 230, 254, 1)",
 "blue4": "rgba(225, 240, 255, 1)",
 "blue3": "rgba(237, 246, 255, 1)",
 "blue2": "rgba(245, 250, 255, 1)",
 "blue1": "rgba(251, 253, 255, 1)",
 "red12": "rgba(57, 19, 23, 1)"
} as const;

export default colors;