// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
 "bp1": "520px",
 "bp2": "900px",
 "bp3": "1200px",
 "bp4": "1800px"
} as const;

export default mediaQueries;