

name: 'Build components'

on:
  push:
    branches:
      - main
      - "feature/*"


jobs:
  build-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: 'packages/component-library'
        run: yarn

      - name: Build components
        working-directory: 'packages/component-library'
        run: |
          npx figmagic --token ${{ secrets.FIGMA_TOKEN }} --url ${{ secrets.FIGMA_URL }}
          yarn build
      # See: https://www.chromatic.com/docs/github-actions
      - name: Publish to Chromatic

        if: github.ref != 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          workingDir: 'packages/component-library'
          exitZeroOnChanges: true
          exitOnceUploaded: true
